# Сервис базы данных PostgreSQL
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Основное приложение, содержащее два сервиса
  app:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт greeting-service
      - "8081:8081"  # Порт counter-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: counter_db

# Том для хранения данных PostgreSQL
volumes:
  postgres_data:
